### ISSUE TITLE
[Feature Request]: Create a Pricing Page

### ISSUE THREAD

**Issue by Pratik2026** [bsoc-bitbyte/busify#101]
### Is your feature request related to a problem? Please describe.

We need a pricing page to showcase our plans. 

### Describe the solution you'd like

Create a pricing page having free and premium plans showcased as card components. There are so many online templates available for pricing card components. You can refer them.

**Comment by abhijeetw035** [comment]
I would like to work on this issue, i will use online templates for card components and create the required page
