### ISSUE TITLE
[Feature Request]: Create Policy and terms Pages

### ISSUE THREAD

**Issue by Pratik2026** [bsoc-bitbyte/busify#106]
### Is your feature request related to a problem? Please describe.

We need to verify our website in order to receive live API keys for the Razorpay account. For website verification, it must contain pages to define policies and terms & conditions.

### Describe the solution you'd like

Create the following pages with dummy content and add their links in the footer:
- Privacy Policy Page
- Terms & conditions
-  Refund/Cancellation Policy

For design & content, you can browse online templates of these pages for ticket booking service applications.

### Developer Help

Keep me posted about content & designs through the Discord.

**Comment by abhijeetw035** [comment]
@Pratik2026 i would like to work on this issue, i will use online templates for page and create the required page

**Comment by Pratik2026** [comment]
@abhijeetw035, Sure go ahead.
