### ISSUE TITLE
Add a toast error if user is not logged in

### ISSUE THREAD

**Issue by prajjwalkapoor** [bsoc-bitbyte/busify#11]
![image](https://github.com/bsoc-bitbyte/busify/assets/68912239/b308d5f3-6062-4f74-9a10-8ec88569e7e9)

Add a toast showing an error if the user is not logged in. Use should use [this npm package](https://www.npmjs.com/package/react-hot-toast)

**Comment by parthksingh1** [comment]
Sir i would like to contribute to this issue, please assign it to me

**Comment by prajjwalkapoor** [comment]
@parthksingh1 the blocker for this issue is now cleared, you can now start working on this.

**Comment by parthksingh1** [comment]
Sure 
Will Start working on it .
