### ISSUE TITLE
Create bus ticket component

### ISSUE THREAD

**Issue by prajjwalkapoor** [bsoc-bitbyte/busify#14]
![image](https://github.com/bsoc-bitbyte/busify/assets/68912239/a9f1b94f-4f16-4135-9fdb-06f68421f92d)

Create a bus ticket component according to Figma design.
Data on the component should be dynamic and should be passed as a prop. 

example data: 
```
const ticketData = {
checkpoints: ['Nescafe', 'Railway Station', 'Reliance Fresh'],
time: '3:30 PM',
price: 20,
seatsLeft: 45 
}
```
You should make it like `<BusTicket ticketData={ticketData} />`. Use MUI components and styling.

**Comment by jainvedant392** [comment]
Sir, I would like to contribute to this issue. May I get this issue assigned please ?

**Comment by prajjwalkapoor** [comment]
Sure @jainvedant392, I'm assigning it to you.

**Comment by jainvedant392** [comment]
@prajjwalkapoor, I had a doubt regarding this issue. Do I have to create a bus ticket for a single data object for now, as provided in the example, or is there any file, where an array of many objects is stored, which I can import and work with ?
Please help me with this doubt .

**Comment by jainvedant392** [comment]
And one more thing, will the tickets be displayed on clicking the "See Schedule" button ?

**Comment by prajjwalkapoor** [comment]
> @prajjwalkapoor, I had a doubt regarding this issue. Do I have to create a bus ticket for a single data object for now, as provided in the example, or is there any file, where an array of many objects is stored, which I can import and work with ? Please help me with this doubt .

you can create an array with demo data, and the loop through that
