### ISSUE TITLE
Create a bus search component

### ISSUE THREAD

**Issue by prajjwalkapoor** [bsoc-bitbyte/busify#15]
![image](https://github.com/bsoc-bitbyte/busify/assets/68912239/256abce4-4dc4-4df5-a1dc-9734bfdb83fa)

Create the UI for the search component to search buses between two points. Since the issue is a little bit complex, so you have to collaborate with @Bhavik-ag and @mittalvansh. 

If you have ideas on how we can make this, feel free to comment here.

**Comment by Sakshi-Singhroha** [comment]
please assign me this issue

**Comment by prajjwalkapoor** [comment]
@Sakshi-Singhroha this is a little bit complex issue so we have to discuss how you will gonna approach this issue. Feel free to share your ideas on Discord.
