### ISSUE TITLE
Create the home page 

### ISSUE THREAD

**Issue by prajjwalkapoor** [bsoc-bitbyte/busify#16]
![image](https://github.com/bsoc-bitbyte/busify/assets/68912239/8c8b2515-bdd4-4cf3-9fb6-f480ca3e7540)

Create the home page as per the Figma design and use MUI Grids to make it responsive. The navbar, search component and footer is part of different issue so you can skip that part.

**Comment by Sakshi-Singhroha** [comment]
Please assign me this issue.

**Comment by prajjwalkapoor** [comment]
@Sakshi-Singhroha sure, you can now work on this.

**Comment by prajjwalkapoor** [comment]
Hi @Sakshi-Singhroha, there is a slight change in the UI. I have updated the above image, kindly look into it and make the UI accordingly.

**Comment by abansal15** [comment]
hello @prajjwalkapoor  i would like to work on the issue could u pls assign it to me

**Comment by rrtk857** [comment]
@prajjwalkapoor, Please assign me this issue.

**Comment by prajjwalkapoor** [comment]
Guys, this issue is already assigned to @parthksingh1. You guys can take any other issue.
