### ISSUE TITLE
To add the favicon to the site

### ISSUE THREAD

**Issue by abansal15** [bsoc-bitbyte/busify#19]
Create a favicon for busify.

**Comment by abansal15** [comment]
hell0 @prajjwalkapoor i would like to work on the issue could you please assign it to me

**Comment by jainvedant392** [comment]
@prajjwalkapoor, I would like to contribute to this issue. Could you please assign this work to me ? I will browse for a nice favicon, suitable for our project, and then link it in the header of the main HTML file.

**Comment by prajjwalkapoor** [comment]
Sure @jainvedant392 you can work on this.

**Comment by jainvedant392** [comment]
@prajjwalkapoor , do I also have to change the title in the main HTML file, while adding the favicon
