### ISSUE TITLE
Designing a structure for Admin Panel 

### ISSUE THREAD

**Issue by prajjwalkapoor** [bsoc-bitbyte/busify#20]
By designing I mean:
- [ ] Listing down the functional and non-functional requirements
- [ ] Prototyping the User Interface
- [ ] Listing down routes for the backend

Feel free to share your ideas here.

**Comment by prajjwalkapoor** [comment]
@satcode8 Sure! Share your ideas.

**Comment by satcode8** [comment]
Sir in the admin panel the functional requirements can be:
1). Bus Data manager: Which allows the admin to add/edit/delete details of a particular bus or it's route.
2). Ticket Manager: Allows the admin to access data on number of tickets booked/cancelled/refunds.
3). User Data: Allows admin to access a user's ticketing history.
4). Customer support: Allows admin to respond to any requests/queries by the end user.
5). Announcements/Notifications Tab : Allows admin to make any urgent/important announcements about bus details/delays etc.

The non-functional requirements can be: 
1). Scalability: The website should be able to handle increased load at peak times.
2). Compatibility: The admin should be able to use the admin panel from any device.
3). Usability: A well organised user interface which has efficient navigation.
4). Analytics: Provides long term data and reports for the admin which they can use to make informed decisions

**Comment by satcode8** [comment]
How do I prototype the UI sir?

**Comment by varun7singh** [comment]
@satcode8 refrain from using sir :)
