### ISSUE TITLE
[Feature Request]: add avatar image in navbar

### ISSUE THREAD

**Issue by prajjwalkapoor** [bsoc-bitbyte/busify#25]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/bsoc-bitbyte/busify/assets/68912239/46ed3f61-7793-4e75-a1ae-0df976d91057)

Currently, the navbar only shows the name of the currently logged-in user which is incomplete.

### Describe the solution you'd like

![image](https://github.com/bsoc-bitbyte/busify/assets/68912239/0cbe7c1c-c463-4050-b1b3-8eda4a930f2f)

Add the Avatar image.

### Developer Help

https://mui.com/material-ui/react-avatar/

Use the MUI avatars for this.

**Comment by satcode8** [comment]
I would like to work on this issue.pls a

**Comment by prajjwalkapoor** [comment]
@satcode8 sure!

**Comment by prajjwalkapoor** [comment]
@satcode8 updates?

**Comment by Doraemon012** [comment]
Sir, I can take the profile image of the user from the database, and then I can render the same to the webpage using an image tag.
Sir, I would like to work on this issue, please assign it to me.

**Comment by prajjwalkapoor** [comment]
Sure @Doraemon012 you can work on this.
