### ISSUE TITLE
[Feature Request]: style default scrollbar

### ISSUE THREAD

**Issue by prajjwalkapoor** [bsoc-bitbyte/busify#26]
### Is your feature request related to a problem? Please describe.

Currently, the default scrollbar looks ugly.

### Describe the solution you'd like

style the scrollbar under global styling.

**Comment by Doraemon012** [comment]
Sir, I would like to work on this issue. Please assign this to me.

**Comment by prajjwalkapoor** [comment]
@Doraemon012 you can now work on this issue.
