### ISSUE TITLE
[BUG]: Make the bus details drawer responsive

### ISSUE THREAD

**Issue by prajjwalkapoor** [bsoc-bitbyte/busify#28]
### Describe the bug

Currently, the bus details drawer is not responsive. 

### Steps To Reproduce

Reduce the screen size

### Expected Behavior

It should be fully responsive for mobile, tablet and desktop layout.

### Screenshots/Videos

![image](https://github.com/bsoc-bitbyte/busify/assets/68912239/6322178c-20bb-4f9b-9d54-c0692946d811)

### What device are you using?

Desktop, Mobile

**Comment by prajjwalkapoor** [comment]
If you need any help regarding this, just ask @mittalvansh.

**Comment by shramanpaul** [comment]
I want to implement a fluid grid layout proportionally and will use percentages or rem to define the width and height instead of Pixels.

**Comment by prajjwalkapoor** [comment]
You can now work on this @shramanpaul
