### ISSUE TITLE
[Feature Request]: react custom hook for data fetching

### ISSUE THREAD

**Issue by prajjwalkapoor** [bsoc-bitbyte/busify#38]
### Is your feature request related to a problem? Please describe.

Currently, we are writing repetitive code for data fetching which violates the DRY principle.

### Describe the solution you'd like

Make a react custom hook something like `useFetch` for data fetching.
Make sure you will handle the method, URL ( Fix the host and fetch it from env, just change the path ), allowCookie, payloads etc. You should use Axios for fetching.

**Comment by RISHIKESHk07** [comment]
@prajjwalkapoor i would like  to contribute to this issue

**Comment by prajjwalkapoor** [comment]
Sure, go ahead @RISHIKESHk07

**Comment by prajjwalkapoor** [comment]
any updates @RISHIKESHk07?

**Comment by RISHIKESHk07** [comment]
@prajjwalkapoor I been working on the issue ,had problem with backend on docker ,retrying the process with linux  as of now

**Comment by RISHIKESHk07** [comment]
```js
import { useState, useEffect } from 'react';
import axios from 'axios';
const useFetch = (url) => {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchData = async () => {
      setLoading(true);
      try {
        const res = await axios.get(url);
        setData(res.data);
        setError(null);
      } catch (err) {
        setError(err);
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, [url]);

  return { data, loading, error };
};
```
this the one solution i came up with

**Comment by RISHIKESHk07** [comment]
@prajjwalkapoor  where should this change go.
