### ISSUE TITLE
[Feature Request]: Refactor styles for HeroContainer component in homepage.

### ISSUE THREAD

**Issue by jainvedant392** [bsoc-bitbyte/busify#44]
### Is your feature request related to a problem? Please describe.

The text and button in HeroContainer have some alignment issues, as the dimensions of the latter are dynamic, with changing viewports.
</br>
![Screenshot (23)](https://github.com/bsoc-bitbyte/busify/assets/129421822/6c565f01-c1a8-4379-bbb4-851b51cd8bb3)
![Screenshot (25)](https://github.com/bsoc-bitbyte/busify/assets/129421822/3a7fd7eb-710f-4cd0-95a4-8b2b850d2206)
![Screenshot (27)](https://github.com/bsoc-bitbyte/busify/assets/129421822/04f233d1-6f2a-4a11-a3ec-85d42c658ad2)

### Describe the solution you'd like

make the dimensions in rem instead of "vw", "vh" or percentage, suitable to different breakpoints.

**Comment by Doraemon012** [comment]
I would like to work on this issue. I will use rem to make the hero container responsive.

**Comment by prajjwalkapoor** [comment]
@Doraemon012 actually Vedant is working on that, you can take other issues.
