### ISSUE TITLE
Add a manage busses button if the user is an admin.

### ISSUE THREAD

**Issue by prajjwalkapoor** [bsoc-bitbyte/busify#47]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/bsoc-bitbyte/busify/assets/68912239/c1f5e379-06b0-4e72-b5bc-a77b2fb1b75e)

It should look like this. And also it should not be visible on mobile screens.

### Describe the solution you'd like

NA

**Comment by Doraemon012** [comment]
@prajjwalkapoor please assign this to me. I will check if the user is an admin, and add a manage buses button.
