### ISSUE TITLE
Create a AdminSidebar component for admin panel

### ISSUE THREAD

**Issue by prajjwalkapoor** [bsoc-bitbyte/busify#48]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/bsoc-bitbyte/busify/assets/68912239/0d49f732-25fa-4100-8add-14d2763c8050)

Also, make it mobile responsive.

### Describe the solution you'd like

NA

**Comment by Doraemon012** [comment]
@prajjwalkapoor I would like to contribute to this issue, please assign this to me. I will use the MUI - react drawer component for this.

**Comment by prajjwalkapoor** [comment]
Sure, go ahead @Doraemon012.
