### ISSUE TITLE
Create a UserProtectedRoute component

### ISSUE THREAD

**Issue by prajjwalkapoor** [bsoc-bitbyte/busify#49]
### Is your feature request related to a problem? Please describe.

Some routes like `/checkout` should be protected if the user is not logged in. Design a component that will act as a wrapper to a page and redirects users to the home page if they are not logged in.

For Example: 
```
<UserProtectedRoute>
    <Checkout />
</UserProtectedRoute>
```

### Describe the solution you'd like

NA

**Comment by Pratik2026** [comment]
I would like to work on this issue. I will simply create a userProtectedRoute component which will redirect the user to home page if they are not logged in otherwise rendered the wrapped Component .

**Comment by prajjwalkapoor** [comment]
@Pratik2026 sure
