### ISSUE TITLE
Create a AdminProtectedRoute component

### ISSUE THREAD

**Issue by prajjwalkapoor** [bsoc-bitbyte/busify#50]
### Is your feature request related to a problem? Please describe.

Some routes like `/admin/dashboard` must not be accessed by the user except an admin. Design an `AdminProtectedRoute` component that will act as a wrapper to a page and redirect users to the home page if they don't have an admin role.

For Example: 
```
<AdminProtectedRoute>
    <AdminDashboard />
</AdminProtectedRoute>
```

### Task
- Create an AdminProtectedRoute component.
- Rename the `admin `page folder and its component to `AdminDashBoard`.
- Replace the `/admin` route to `admin/dashboard` and render the `AdminDashBoard `page there.
- Wrap the AdminDashboard with your AdminProtectedRoute component.

### Developer Help

You can refer to the last tear contributor's [PR](https://github.com/bsoc-bitbyte/busify/pull/62). Significant work has already been done there.

**Comment by parthksingh1** [comment]
I would like to work on this issue. I will simply create a AdminProtectedRoute component which will redirect the user to home page if they are not admin otherwise rendered the wrapped Component .

**Comment by prajjwalkapoor** [comment]
@parthksingh1 sure

**Comment by bravichandra12** [comment]
@Pratik2026 
I would like to work on this issue. I will create Admin Protected Route Component and will make sure to navigate it to home page if user is not admin

**Comment by Pratik2026** [comment]
Sure @bravichandra12, you can start working on it.
