### ISSUE TITLE
Create a AdminPageLayout component for admin pages.

### ISSUE THREAD

**Issue by prajjwalkapoor** [bsoc-bitbyte/busify#51]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/bsoc-bitbyte/busify/assets/68912239/22d8fdb8-3c04-48f9-9148-abbdbb3f42a4)

The layout should be static for all the admin pages with a sidebar specific to the admin pages and header.  

### Describe the solution you'd like

NA

**Comment by Doraemon012** [comment]
Sir, I would like to work on this issue. For sidebar, I can use the MUI React drawer component. I can use rem or em to make the page responsive.
