### ISSUE TITLE
Redirect user from checkout page if visited directly through URL

### ISSUE THREAD

**Issue by Bhavik-ag** [bsoc-bitbyte/busify#57]
### Is your feature request related to a problem? Please describe.

- When user directly visits the checkout page using the page URL, the checkout details are empty.

### Describe the solution you'd like

- User should only be allowed to visit checkout page through bus schedule page and not directly.

### Developer Help

- Add a check on checkout page to redirect user to schedule if directly visited through URL.
- This can be achived by looking passengers value in local state.

**Comment by Pratik2026** [comment]
I would like to work on this issue. Please assign it to me
