### ISSUE TITLE
[Feature Request]: Create a profile page

### ISSUE THREAD

**Issue by prajjwalkapoor** [bsoc-bitbyte/busify#58]
### Is your feature request related to a problem? Please describe.

Create a profile page that can show the user's name, profile picture, Email ID, member since and all of their past orders. 
Note: Figma designs are not available for the profile page, so you must create one.

### Describe the solution you'd like

You can create a separate component may be `PastOrderCard` and then loop through all the user's past orders.

**Comment by prajjwalkapoor** [comment]
Sure @anshikkay but no need to use tailwind, just mui components with custom styling are enough.

**Comment by anshikkay** [comment]
@prajjwalkapoor sure 👍

**Comment by jainvedant392** [comment]
Hey @prajjwalkapoor , I can work on it.

**Comment by prajjwalkapoor** [comment]
@jainvedant392 any update on this?

**Comment by jainvedant392** [comment]
Yes cloned the repo and saw the figma design for it. Started making slight changes to the design.

**Comment by jainvedant392** [comment]
Will keep you updated
