### ISSUE TITLE
Remove rupee symbol from ticket quantity

### ISSUE THREAD

**Issue by prajjwalkapoor** [bsoc-bitbyte/busify#59]
### Describe the bug

![image](https://github.com/bsoc-bitbyte/busify/assets/68912239/95996e15-cb61-4147-8cbb-14116c076949)
Remove the rupee symbol from the ticket quantity and also change"NET AMOUNT TO PAY" to "TOTAL".

**Comment by ojasvatomar47** [comment]
I would like to work on this issue. Please assign it to me

**Comment by prajjwalkapoor** [comment]
Sure @ojasvatomar47, you can now work on this.
