### ISSUE TITLE
Create recent order card for admin panel

### ISSUE THREAD

**Issue by prajjwalkapoor** [bsoc-bitbyte/busify#60]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/bsoc-bitbyte/busify/assets/68912239/96cd5551-9377-443e-b902-99cba07abf7c)
Create with any demo data for now, later we can use the response from backend.

### Describe the solution you'd like

NA

**Comment by Doraemon012** [comment]
@prajjwalkapoor, please assign this issue to me, I will create a card using the MUI- card component.
