### ISSUE TITLE
[Feature Request]:  Replace "Write Passengers Roll no" with "Write passenger's Email ID."

### ISSUE THREAD

**Issue by parthksingh1** [bsoc-bitbyte/busify#64]
### Is your feature request related to a problem? Please describe.

Replace "Write Passengers Roll no" to "Write passenger's Email ID." This change is necessary to accurately capture the required information from the user. By requesting the passenger's email ID instead of roll numbers, you are expanding the scope of data collection to include a more comprehensive and essential piece of information.
By including email IDs, not only students but also parents and other staff members can book tickets.

### Describe the solution you'd like

Replace "Write Passengers Roll no" with "Write passenger's Email ID."

**Comment by parthksingh1** [comment]
I would like to work on this issue

**Comment by prajjwalkapoor** [comment]
yeah sure, make sure you also validate the email pattern on the frontend side.
