### ISSUE TITLE
implement navbar component as per figma design

### ISSUE THREAD

**Issue by Bhavik-ag** [bsoc-bitbyte/busify#7]
**Tasks**
- Implement the navbar component as per the figma design
- Create a separate component for the `Sign in with Google` button
- Make sure to use Material UI components only
- Try to make it responsive 

**For Reference**
- Figma design - [Link](https://www.figma.com/file/DCKxO44wwjeAxmUHLvZ5wT/Busify?type=design&node-id=1-2&t=fcP7ZsrAa7ssDB65-0)
- Material UI docs - [Button](https://mui.com/material-ui/react-button/)

**Comment by prajjwalkapoor** [comment]
@younome71 try to use the MUI grids for responsiveness.

**Comment by younome71** [comment]
Ok sir

**Comment by prajjwalkapoor** [comment]
@younome71 any updates?
