### ISSUE TITLE
Create a AdminPageLayout component for admin pages.

### ISSUE THREAD

**Issue by Pratik2026** [bsoc-bitbyte/busify#75]
### Is your feature request related to a problem? Please describe.

We will be having multiple pages involving the admin panel sidebar, a Navbar & a Footer as you can see in the below image. This will cause the redundancy in the codebase.

![image](https://github.com/bsoc-bitbyte/busify/assets/128511266/ac6cc187-77e4-48a2-9d12-4bc48333a852)

### Describe the solution you'd like

Create an `AdminPageLayout` component. The layout component is the wrapper that contains common components and wraps the different pages. You can learn more about this [here](https://chrisdevcode.hashnode.dev/how-to-create-a-layout-component-react)

### Developer Help

Both AdminSidebar & Footer have been created already. Include the Navbar code in the layout component itself. No need to create a separate navbar component as there's not much in it to do except a "Manage Buses" heading and day subheading (refer to the image).

**Comment by Om-Thorat** [comment]
May I take up this issue,  I plan to create a separate layout component and use the prebuilt adminsidebar and footer, and pass in the prop.children in the main component so it can be used as a layout in other components. Also if needed shall i make a page demonstrating the use of the said layout?

**Comment by Pratik2026** [comment]
@Om-Thorat, you can start working on it.

**Comment by Pratik2026** [comment]
Yeah, you can create a separate page to demonstrate the page layout.
