### ISSUE TITLE
Create a general button component 

### ISSUE THREAD

**Issue by Bhavik-ag** [bsoc-bitbyte/busify#8]
#### Implement a general button component with the following features 
- Custom button label 
- Optional icon field
- Prop to mark the button as disabled
- Tooltip on Button
- Color of the button - primary, warning, alert, success, danger
- Size of the button - small, medium and large
- Optional href prop
- Ghost - Outlined or filled

**Comment by Pratik2026** [comment]
Sir, I would like to work on this issue. Please assign it to me.

**Comment by Pratik2026** [comment]
Sir, I just wanted to confirm that the button component should return a button element that incorporates the requested props and functionality consistent with Material-UI buttons only right?

**Comment by prajjwalkapoor** [comment]
> Sir, I just wanted to confirm that the button component should return a button element that incorporates the requested props and functionality consistent with Material-UI buttons only right?

@Pratik2026 Yes, and you could also add a prop specifying type ( primary, secondary, etc ).
