### ISSUE TITLE
Figma design for mobile screen

### ISSUE THREAD

**Issue by prajjwalkapoor** [bsoc-bitbyte/busify#9]
Create a Figma design for the mobile screen according to the desktop screen design ( [Figma Design Link](https://www.figma.com/file/DCKxO44wwjeAxmUHLvZ5wT/Busify?type=design&node-id=31%3A208&t=7aXZk7qlTON3A8C3-1) )

If you have anything to discuss about the designs, feel free to do it here.

**Comment by RISHIKESHk07** [comment]
sir , could you assign this issue to me ?

**Comment by Doraemon012** [comment]
Sir, I would like to contribute to this issue. Please assign it to me.

**Comment by prajjwalkapoor** [comment]
Sure, just duplicate the above Figma file and start working on that. let me know if you need any help or suggestions.

**Comment by Doraemon012** [comment]
> Sure, just duplicate the above Figma file and start working on that. let me know if you need any help or suggestions.

Sir, means the design for mobile screen should be identical to the one for desktop, or can we make changes in that ?

**Comment by prajjwalkapoor** [comment]
> 

@Doraemon012, not compulsorily identical, but the theme should match and other than that it should follow UX principles.

**Comment by Doraemon012** [comment]
@prajjwalkapoor Sir, do I have to commit this change or should I just share the link of the design ?

**Comment by prajjwalkapoor** [comment]
> @prajjwalkapoor Sir, do I have to commit this change or should I just share the link of the design ?

Just share the link to the Figma file here.

**Comment by Doraemon012** [comment]
### Changes made :

- I have created the Figma design for mobile screen (according to the desktop design).
- I have added some additional things :
        1. Back button (to redirect to the previous page)
        2. "Tickets booked successfully" page (to which the user can be redirected after the tickets have been booked)

- **Link to the design** : https://www.figma.com/file/BLbmPZIKlvliz0OkHQNPg6/Busify-(Copy)?type=design&node-id=8%3A2&t=gXUwDcUMyKElznN7-1
                                                                    





- Sir, I would like to suggest some changes in the design (Mobile and Desktop):
    1. Background color can be changed to a comparatively darker one (#FFF9F9), so that the white components can look brighter.
    2. A "payment successful" page can also be added after the user pays for the ticket.

- I have created one more design (for mobile screen):
- Link to the design: https://www.figma.com/file/6Ct6k1jVz8BWZ5xvHODI91/Duplicate?type=design&node-id=8%3A2&t=fCBpUivBh6MRlNS9-1
- If allowed then, I can make the same changes to the desktop design.

**Comment by prajjwalkapoor** [comment]
Good Work @Doraemon012!
Let's connect on Discord. I'll give you access to the main Figma file, you can copy your designs on that file.
