### ISSUE TITLE
Create a schedule page for admin. 

### ISSUE THREAD

**Issue by Pratik2026** [bsoc-bitbyte/busify#90]
### Is your feature request related to a problem? Please describe.

Currently, there's no page available where the admin can manage the buses schedule.

### Describe the solution you'd like

Create a schedule page which can be visited by clicking on the schedule tab. For now, use the dummy data while creating components.

### Developer Help

- Here's the [Figma Design Link](https://www.figma.com/design/dhFhm64op9fcre1hbsGTab/Busify?node-id=282-686&t=8XsLSQuP8FuuHOzc-0) for reference.
-  In order to view the admin page as an "Admin" role, you can make a slight change in "frontend/src/store/ authstore.tsx" file:
At line 25 :
`setUser: user => set({ user: { ...user, role: 'admin', } }),`

**Comment by bravichandra12** [comment]
@Pratik2026 
I would like to work on this issue, where I will create schedule page for admin using react and MUI and make sure it is accessible by clicking schedule tab.

**Comment by Pratik2026** [comment]
@bravichandra12, sure dm me your email id for Figma access.

**Comment by bravichandra12** [comment]
@Pratik2026 
Sure I will do it and thank you.
