### ISSUE TITLE
[Feature Request]:  Implement the functionality to add new or edit existing bus schedule.

### ISSUE THREAD

**Issue by Pratik2026** [bsoc-bitbyte/busify#94]
### Is your feature request related to a problem? Please describe.

As of now, the schedule page is completely hardcoded and the admin does not have any way to add or edit the bus schedule.

### Describe the solution you'd like

The following task is required to be completed to make the schedule page functional:
- Implement the modal to add and edit the bus schedule data according to the design which will open when the admin clicks on either the `add new` button or `queueCard`(dashed border one).
- Replace the see more text with edit text in both `BusCards` and `ConductorCards`, clicking on which same modal should be open but with existing data written in the fields.
- The admin must be able to add or update the bus schedule using that modal.
- On adding/updating the bus schedule, the schedule page should be rerendered to reflect the recent changes.

### Developer Help

- Here's the [Figma Design Link](https://www.figma.com/design/dhFhm64op9fcre1hbsGTab/Busify?node-id=282-686&t=LhHyoeafOMalYqZ7-0) for reference.
- In order to view the admin page as an "Admin" role, you can make a slight change in "frontend/src/store/ authstore.tsx" file:
At line 25 :
`setUser: user => set({ user: { ...user, role: 'admin', } }),`

**Comment by Om-Thorat** [comment]
Hello, I would like to work in this, I will create and style the frontend using Mui components to change ths schedule and update it in the db I'll use the already present schedule model in prisma and make necessary changes to the bus.controller.ts to alter the schedule. I'll make sure the page is responsive and the data is updated correctly and in accordance to everywhere else where the model is used.

**Comment by Pratik2026** [comment]
@Om-Thorat , sure, you can start working on it.
