### ISSUE TITLE
[Feature Request]: Create a Custom Empty Modal to handle the UI when the data is empty.

### ISSUE THREAD

**Issue by Pratik2026** [bsoc-bitbyte/busify#98]
### Is your feature request related to a problem? Please describe.

Currently, there's nothing to display when the data is empty which is a bad UX. You can see that when you visit either the profile page or the admin dashboard/schedule page, it will display empty space.

### Describe the solution you'd like

Create a custom `Empty` Modal which will display when there is no data. The component should take the `title` and `description` as props.  It should display till the data is empty. This component should be displayed on the following page whenever required:
- Profile page
- Dashboard
- Schedule

To gain more clarity, visit the following link for reference: https://react.keepdesign.io/docs/components/empty#default-empty

### Developer Help

- In order to view the admin page as an "Admin" role, you can make a slight change in "frontend/src/store/ authstore.tsx" file:
At line 25 :
`setUser: user => set({ user: { ...user, role: 'admin', } }),`

**Comment by Vaibhavsahu2810** [comment]
@Pratik2026 i would like to work on this issue.I will create the custom Empty Modal which will display when there is no data.

**Comment by bravichandra12** [comment]
@Pratik2026 
I would like to work on this issue. I will create a custom `empty` modal when there is no data

**Comment by Pratik2026** [comment]
Your previous issue is still pending to be reviewed

**Comment by ShashaankS** [comment]
@Pratik2026 I would like to work on this issue, I will create a custom empty modal when there is no data to display in "Profile, dashboard, schedule " pages, being new to busify this  issue is good to start with.

**Comment by Pratik2026** [comment]
@bravichandra12 You can start working on it.

**Comment by Pratik2026** [comment]
@ShashaankS I appreciate your enthusiasm as a new contributor! We will be opening more good first issues very soon on an FCFS basis. I hope you can take them on.
