### ISSUE TITLE
[Feature Request]: Create an About Page.

### ISSUE THREAD

**Issue by Pratik2026** [bsoc-bitbyte/busify#99]
### Is your feature request related to a problem? Please describe.

Currently, we don't have a dedicated page to showcase the vision and story behind this project.

### Describe the solution you'd like

Create an About page. The page must display our vision and our story. No need to add anything else for now.You can refer to the below links for design inspiration: 
- https://www.hubspot.com/our-story?__hstc=95980867.5d618e8928d5fa2a0891254a6e0bb726.1720156819985.1720156819985.1720156819985.1&__hssc=95980867.1.1720156819985&__hsfp=1054730769
- https://www.vidyard.com/about/

**Comment by ANIRUDHNARANG0** [comment]
@Pratik2026  I would like to work on this issue I would create a simple about page and would style it as required
